---
- name: play1 - configure access-r1-r2 interfaces
  hosts: access
  tasks:
    - name: conf l3 access
      cisco.ios.ios_l3_interfaces:
        config:
        - name: "{{ item.name }}"
          ipv4:
            - address: "{{ item.ipv4 }}"
      loop: "{{ interfaces }}"

    - name: enable l3 access
      cisco.ios.ios_interfaces:
        config:
        - name: "{{ item.name }}"
          enabled: true
      loop: "{{ interfaces }}"

    - name: enable ospf
      cisco.ios.ios_ospf_interfaces:
        config:
        - name: "{{ item.name }}"
          address_family:
            - afi: ipv4
              process:
                id: 1
                area_id: 0
      loop: "{{ interfaces }}"
      when: " item.ospf == true "

    - name: add dns 
      ios_config:
        lines:
        - ip domain-lookup
        - ip name-server 192.168.100.2

    - name: save conf
      ios_command:
        commands:
        - command: 'write memory'
          prompt: 'Overwrite the previous NVRAM configuration?[confirm]'
          answer: 'yes'


