---
interfaces:
  - name: FastEthernet0/0
    ipv4: 10.3.3.1/30
    netmask: 255.255.255.252
    wildcard: 0.0.0.3
    ospf: true
    area: 0

  - name: FastEthernet1/0
    ipv4: 192.168.2.1/24
    netmask: 255.255.255.0
    ospf: true
hst__id: 1